feat: Add Region in school data
Team-IF/comcigan-py pull request #7
Opened 2021-09-02 11:24 UTC by kms0219kms

가끔 학교 이름은 같은데 지역이 다른 경우가 있습니다.

이런 경우를 대비하여 검색 데이터에 지역값을 같이 제공하게 하면 좋을 것 같아 의견 드립니다.

2021-09-02 11:25 UTC, kms0219kms commented
왜 Travis CI가 에러가 나는지 모르겠습니다. 코드에는 문제가 없습니다.

2021-09-11 10:02 UTC, kiki7000 requested changes
__slots__에 "region" 추가해주세요

2021-09-11 10:04 UTC, kiki7000 requested changes
AsyncSchool에도 똑같이 region 프로퍼티 추가해주세요

2021-09-14 11:13 UTC, kms0219kms commented
네

2021-09-14 11:18 UTC, kms0219kms commented
수정하엿습니다.

2021-09-14 11:52 UTC, kiki7000 commented
AsyncSchool __slots__에도 추가하셔야 합니다

2021-09-15 23:33 UTC, kms0219kms commented
모두 추가하였습니다 ..

2021-09-16 00:00 UTC, kiki7000 approved these changes

2021-09-16 00:14 UTC, kiki7000 commented
LGTM

2021-09-16 00:14 UTC, merged